[General]
# Path to the background image
background=Assets/background.png

# Font Family
fontFamily="Fira Sans, Noto Sans, sans-serif"

# Card Drop shadows [true | false]
dropShadows=false

# Blur radius for the background [numbers]
blurRadius=0

# Card Opacity [0 to 1]
cardOpacity=0.95

# Power Buttons radius (roundness)
buttonRadius=20

# Password input radius (roundness)
passwordInputRadius=20

# Card Border radius (roundness)
cardRadius=20

# Color Scheme
# Do not touch these if you are using color-sync
mPrimary=#5f93ec
mOnPrimary=#181d25

mSecondary=#5e48ea
mOnSecondary=#181d25

mTertiary=#ae48ea
mOnTertiary=#181d25

mError=#fd4663
mOnError=#181d25

mSurface=#061837
mOnSurface=#f2f2f3

mSurfaceVariant=#0f2a57
mOnSurfaceVariant=#afb1b6

mOutline=#5e6573
mShadow=#061837

mHover=#ae48ea
mOnHover=#181d25
