color0 #061837
color1 #fd4663
color2 #5f93ec
color3 #5e48ea
color4 #ae48ea
color5 #8db2f1
color6 #9a8df2
color7 #f2f2f3
color8 #5e6573
color9 #fd4663
color10 #5f93ec
color11 #5e48ea
color12 #ae48ea
color13 #8db2f1
color14 #9a8df2
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #061837
background            #061837
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #092049
active_border_color   #5f93ec
inactive_border_color #092049
url_color             #5f93ec

active_tab_foreground   #181d25
active_tab_background   #5f93ec
inactive_tab_foreground #afb1b6
inactive_tab_background #092049
cursor_trail_color      #afb1b6
