color0 #202b31
color1 #fd4663
color2 #add6f1
color3 #d6c85c
color4 #cab7e7
color5 #92c9ec
color6 #e9df96
color7 #f2f2f3
color8 #616b71
color9 #fd4663
color10 #add6f1
color11 #d6c85c
color12 #cab7e7
color13 #92c9ec
color14 #e9df96
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #182025
background            #182025
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #202b31
active_border_color   #add6f1
inactive_border_color #202b31
url_color             #add6f1

active_tab_foreground   #182025
active_tab_background   #add6f1
inactive_tab_foreground #afb3b6
inactive_tab_background #202b31
cursor_trail_color      #afb3b6
